# Action to perform podcast duplicate record analysis

name: duplicates

on:
  push:
   branches: [main, master]
   paths:
    - 'duplicate_runner.R'
  #release:
  schedule:
  - cron: "5 8 * * 0"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      # Give default GITHUB_TOKEN write permission to commit and push the changed files back to repo.
      contents: write
      
    steps:
      - name: Checkout
        id: checkout-step
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          logger: pretty
          log-directives: nix_installer=trace
          backtrace: full

      - name: Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main
  
      - name: Build development environment
        run: |
          nix-build
        
      - name: Perform depuplication
        id: deduplication-step
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ENDPOINT: ${{ secrets.ENDPOINT }}
        run: nix-shell --run "Rscript duplicate_runner.R"
