# Action to perform podcast duplicate record analysis

name: duplicates

on:
  push:
   branches: [main, master]
   paths:
    - 'duplicate_runner.R'
  #release:
  schedule:
  - cron: "5 8 * * 0"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      # Give default GITHUB_TOKEN write permission to commit and push the changed files back to repo.
      contents: write
      
    steps:

      - name: Checkout
        id: checkout-step
        uses: actions/checkout@v4

      - name: Install jq for parsing system dependencies
        id: install-jq-step
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: jq
          version: 1.0
      
      - name: Install system dependencies
        id: install-deps-step
        uses: awalsh128/cache-apt-pkgs-action@latest
        env:
          DEPS_ENV: ${{ steps.parse-dep-step.DEPS_ENV }}
        with:
          packages: libarchive-dev libcurl4-openssl-dev libssl-dev make

      - name: Setup r2u
        id: r2u-step
        uses: eddelbuettel/github-actions/r2u-setup@master
        
      - name: SessionInfo
        id: sessioninfo-step
        run: R -q -e 'sessionInfo()'

      - name: Install deps R package
        id: r-pkg-deps-step
        run: Rscript -e 'install.packages("deps")'
        
      - name: Package Dependencies
        id: r-package-dependencies-step
        # takes advantage of r2u to install the named CRAN packages as binaries
        # in the r2u context we could also use script 'install.r' 
        #run: Rscript -e 'install.packages(c("tinyspotifyr", "ggplot2", "anytime", "data.table", "tinythemes"))'
        run: Rscript -e 'deps::install()'
        
      - name: Perform depuplication
        id: deduplication-step
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ENDPOINT: ${{ secrets.ENDPOINT }}
        run: Rscript duplicate_runner.R
